name: web_test
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  provider: ^6.0.2
  vrouter: ^1.2.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
